CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  BIGINT   NOT NULL,
    quantity    INTEGER  NOT NULL,
    total_price DECIMAL  NOT NULL,
    status      VARCHAR(20) default 'pending',
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);
